- backend/app/recommender/operations.py
- backend/app/requests/__init__.py
- backend/app/routes/recommend.py
- backend/app/routes/search.py
- backend/app/solr/operations.py
- backend/pyproject.toml
- dc-test.yml
Query fields (qf) is necessary in order to be able to query a custom subset
of documents. Otherwise the default Solr schema searches a common _text_ field.
But this has several drawbacks:
- the index is twice the size, since all fields must be copied there,
- query value transformations (e.g. n-grams) cannot be applied directly on a selected field,
- the choice on what fields to search is done when designing a schema, not when
  calling the ESS.
Add also filter query (fq) to filter results by specific fields, apart from filtering by q.
Closes: #18.
> Add query fields and filter query to search params

- .github/workflows/backend-styles.yml
- .github/workflows/ui-styles.yml
- ui/.eslintignore
- ui/.eslintrc.json
- ui/.prettierrc.json
- ui/angular.json
- ui/package-lock.json
- ui/package.json
- ui/src/app/app-routing.module.ts
- ui/src/app/app.component.spec.ts
- ui/src/app/app.component.ts
- ui/src/app/app.module.ts
- ui/src/app/articles-page/articles-page.component.html
- ui/src/app/articles-page/articles-page.component.spec.ts
- ui/src/app/articles-page/articles-page.component.ts
- ui/src/app/auth.interceptor.ts
- ui/src/app/main-header.component.ts
- ui/src/app/marketplace-page/marketplace-page.component.html
- ui/src/app/marketplace-page/marketplace-page.component.spec.ts
- ui/src/app/marketplace-page/marketplace-page.component.ts
- ui/src/app/mocks-service.service.spec.ts
- ui/src/app/mocks.service.ts
- ui/src/environments/environment.ts
- ui/src/index.html
- ui/src/main.ts
- ui/src/polyfills.ts
- ui/src/styles.scss
- ui/src/test.ts
> chore: add linting to UI

- ui/apps/ui/src/app/pages/landing-page/landing-page.component.html
- ui/libs/pages/search/src/lib/components/filters/filters.component.ts
All green selected errors from: https://docs.google.com/document/d/1shX7kEAhmYJQq3jRa9D8Zx94eXUiYy5DZ0Grot21OOY/edit#
> fix: minor fixes

- ui/apps/ui/src/index.html
- ui/apps/ui/src/scss/landing.scss
- ui/apps/ui/src/styles.scss
- ui/libs/layout/src/lib/components/sub-header/sub-header.component.ts
- ui/libs/layout/src/lib/components/sub-nav/sub-nav.component.ts
- ui/libs/pages/search/src/lib/components/active-filters/active-filters.component.ts
- ui/libs/pages/search/src/lib/components/filters/filters.component.ts
- ui/libs/pages/search/src/lib/components/result/result.component.ts
- ui/libs/pages/search/src/lib/pages/search-page/search-page.component.ts
- ui/package-lock.json
- ui/package.json
* RWD mods
* minor css mods
* results list css
* first css mods
> feat: style results

- backend/app/generic/models/presentable.py
- backend/app/routes/web/__init__.py
- backend/app/routes/web/presentable.py
- backend/app/solr/operations.py
- backend/tests/app/routes/test_search.py
This PR contains backend implementation of endpoint to get items from the database.
Needed for further work with styles
> [#140] Add backend endpoint for get_item

- ui/libs/pages/search/src/lib/components/result/result.component.ts
Add `show_more` button to the description if
it's too long.
Closes #125
> feature: [#125] Add `show_more` button in description

- backend/app/generic/models/presentable.py
- backend/app/recommender/operations.py
- ui/angular.json
- ui/apps/ui/src/app/app.module.ts
- ui/apps/ui/src/scss/landing.scss
- ui/apps/ui/src/styles.scss
- ui/libs/pages/search/src/lib/components/result/result.component.ts
- ui/libs/pages/search/src/lib/pages/search-page/search-page.component.scss
- ui/libs/pages/training/.eslintrc.json
- ui/libs/pages/training/README.md
- ui/libs/pages/training/jest.config.js
- ui/libs/pages/training/project.json
- ui/libs/pages/training/src/index.ts
- ui/libs/pages/training/src/lib/pages-training.module.ts
- ui/libs/pages/training/src/lib/pages/training-detail-page/training-detail-page.component.html
- ui/libs/pages/training/src/lib/pages/training-detail-page/training-detail-page.component.scss
- ui/libs/pages/training/src/lib/pages/training-detail-page/training-detail-page.component.spec.ts
- ui/libs/pages/training/src/lib/pages/training-detail-page/training-detail-page.component.ts
- ui/libs/pages/training/src/lib/state/index.ts
- ui/libs/pages/training/src/lib/state/item.service.ts
- ui/libs/pages/training/src/test-setup.ts
- ui/libs/pages/training/tsconfig.json
- ui/libs/pages/training/tsconfig.lib.json
- ui/libs/pages/training/tsconfig.spec.json
- ui/libs/search/src/lib/collections/trainings/tranings.collection.ts
- ui/tsconfig.base.json
https://github.com/cyfronet-fid/eosc-search-service/issues/140
> [#140] training catalogue

- ui/apps/ui/src/styles.scss
- ui/libs/pages/search/src/lib/components/result/result.component.ts
> [#154] Search results new view

- ui/apps/ui/src/app/components/filters/filter-multiselect/filter-multiselect.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/styles.scss
> 177 UI improvements in ss

- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/styles.scss
> search results tags colors

- ui/apps/ui/src/app/components/search-input/search-input.component.ts
- ui/apps/ui/src/app/components/search-input/search-input.service.ts
- ui/apps/ui/src/app/pages/landing-page/landing-page.component.html
> fix: [#175] Improve behaviour of the search bar

- README.md
- backend/Pipfile
- backend/Pipfile.lock
- backend/app/config.py
- backend/app/dependencies/user_actions.py
- backend/app/middlewares.py
- backend/app/routes/web/auth.py
- backend/app/routes/web/user_actions.py
- backend/app/schemas/session_data.py
- backend/pyproject.toml
- backend/tests/app/routes/test_search.py
- backend/tests/app/routes/test_user_actions.py
- backend/tests/conftest.py
- dc-test.yml
- docker-compose.yml
- ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.ts
> feat: [#191] Add user actions

- transform/all_collection/spark/transform_df/trainings_transform.py
- transform/all_collection/spark/utils/common_df_transformations.py
> feat: convert trainings id

- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/styles.scss
mods of CSS for search reslut list
> search results box css mods

- ui/apps/ui/src/app/app.routing.module.ts
- ui/apps/ui/src/app/pages/acceptable-use-policy/acceptable-use-policy.component.html
- ui/apps/ui/src/app/pages/acceptable-use-policy/acceptable-use-policy.component.scss
- ui/apps/ui/src/app/pages/acceptable-use-policy/acceptable-use-policy.component.spec.ts
- ui/apps/ui/src/app/pages/acceptable-use-policy/acceptable-use-policy.component.ts
- ui/apps/ui/src/app/pages/acceptable-use-policy/acceptable-use-policy.module.ts
- ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.component.html
- ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.component.scss
- ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.component.spec.ts
- ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.component.ts
- ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.module.ts
* Add static page for privacy policy
* Add static page for terms of use
The pages are available under: `/privacy-policy` and `/acceptable-use-policy`
Closes #228
> feat: [#228] Add privacy policy and terms of use

- ui/apps/ui/src/app/components/search-input/search-input.component.ts
> fix: [#259] Autocomplete resource link

- transform/all_collection/spark/transformations/commons.py
- transform/all_collection/spark/transformations/datasets_transform.py
- transform/all_collection/spark/transformations/publications_transfrom.py
- transform/all_collection/spark/transformations/services_transform.py
- transform/all_collection/spark/transformations/software_transfrom.py
- transform/all_collection/spark/transformations/trainings_transform.py
- transform/all_collection/spark/utils/loader.py
> feat: map publisher

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/all/filters.data.ts
- ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
- ui/apps/ui/src/app/collections/data/datasets/filters.data.ts
- ui/apps/ui/src/app/collections/data/openair.model.ts
- ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
- ui/apps/ui/src/app/collections/data/publications/filters.data.ts
- ui/apps/ui/src/app/collections/data/software/adapter.data.ts
- ui/apps/ui/src/app/collections/data/software/filters.data.ts
> fix: add missing tags

- ui/apps/ui/src/app/components/recommendations/recommendations.service.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/app/components/search-input/search-input.component.ts
> fix: hide show more btn on short txt

- ui/apps/ui/src/app/components/search-input/search-input.component.ts
- ui/apps/ui/src/app/components/search-input/search-input.service.ts
> fix: remove search suggestions duplicated groups

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
- ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
- ui/apps/ui/src/app/collections/data/services/adapter.data.ts
- ui/apps/ui/src/app/collections/data/software/adapter.data.ts
- ui/apps/ui/src/app/collections/data/trainings/adapter.data.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
> fix: remove empty tag properties

- ui/apps/ui/src/app/components/recommendations/recommendations.component.scss
- ui/apps/ui/src/app/components/search-bar/search-bar.component.ts
- ui/apps/ui/src/app/pages/landing-page/landing-page.component.html
- ui/apps/ui/src/scss/landing.scss
- ui/apps/ui/src/styles.scss
solves basic mobile views problems #286
> Basic mobile view for SS

- ui/apps/ui/src/app/collections/data/all/filters.data.ts
- ui/apps/ui/src/app/collections/data/all/search-metadata.data.ts
> feat: add research categorization

- backend/app/routes/web/user_actions.py
- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/data-source.model.ts
- ui/apps/ui/src/app/collections/data/data-sources/filters.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/nav-config.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/index.ts
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html
> feat: add data sources

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/nav-config.data.ts
- ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
- ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
- ui/apps/ui/src/app/collections/data/services/adapter.data.ts
- ui/apps/ui/src/app/collections/data/software/adapter.data.ts
- ui/apps/ui/src/app/collections/data/trainings/adapter.data.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/components/recommendations/recommendations.component.html
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/app/components/search-input/search-input.component.ts
- ui/apps/ui/src/app/components/search-input/utils.ts
- ui/apps/ui/src/app/layouts/colored-tags/colored-tags.component.ts
* restore service url in all collection
* restore data source url in all collection
* disable site reloading on data source btn click when in data source collection tab
* fix redirect of data source from all collections
> fix: minor bug fixes

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
> fix: datasource redirection

- transform/all_collection/spark/transformations/commons.py
> feat: adjust research steps

- backend/app/routes/web/user_actions.py
- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/index.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/adapter.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/filters.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/nav-config.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/search-metadata.data.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/app/layouts/colored-tags/colored-tags.component.ts
**Additional scopes**
- remove cursor query parameter on `type` tag redirection
- fix data sources URL redirection
> feat: add other resources products

- ui/apps/ui/src/app/collections/data/publications/filters.data.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/filter-multiselect.component.ts
- ui/apps/ui/src/app/components/filters/filter-range/filter-range.component.ts
- ui/apps/ui/src/app/components/filters/utils.ts
- ui/apps/ui/src/app/components/recommendations/recommendations.component.ts
- ui/apps/ui/src/app/components/search-input/search-input.component.ts
- ui/apps/ui/src/app/pages/search-page/search-page.component.ts
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.ts
- improvement in loading/rendering time
- improvement rendering while fast-moving between tabs
- fix the `hanging/frozen` window issue
- remove the `Publisher` filter from publications collection
> Improve the App performance

- ui/apps/ui/src/app/collections/filters-serializers/utils.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/utils.ts
- ui/apps/ui/src/app/components/search-input/search-input.service.ts
- ui/apps/ui/src/app/pages/search-page/search-page.component.ts
This is the PR that resolves two issues raised in our backlog:
- Improvement of the search bar - to search more results #272 
- Improvement of search suggestions - directly the same way of working as in the case of search bar #324
> Improvement of search & search suggestions

- backend/app/routes/web/search.py
- backend/app/solr/operations.py
- ui/apps/ui/src/app/collections/data/all/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/config.ts
- ui/apps/ui/src/app/collections/data/data-sources/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/datasets/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/publications/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/services/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/software/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/trainings/search-metadata.data.ts
- ui/apps/ui/src/app/collections/data/utils.ts
- ui/apps/ui/src/app/collections/filters-serializers/utils.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/collections/services/fetch-data.service.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.module.ts
- ui/apps/ui/src/app/layouts/description/description.component.ts
- ui/apps/ui/src/app/layouts/description/description.module.ts
- ui/apps/ui/src/app/layouts/secondary-tags/secondary-tags.component.ts
- ui/apps/ui/src/app/layouts/secondary-tags/utils.ts
- ui/apps/ui/src/app/layouts/tags/tags.component.ts
- ui/apps/ui/src/app/layouts/tags/utils.ts
- ui/apps/ui/src/app/layouts/url-title/url-title.component.ts
- ui/apps/ui/src/app/layouts/utils.ts
- ui/apps/ui/src/environments/environment.common.ts
- ui/package-lock.json
- ui/package.json
look for: `backend/app/solr/operations.py`
> Highlight matched searched phrases in a title, a description, and the tags.

- ui/apps/ui/src/app/components/search-bar/search-bar.component.ts
> feat: [#407] add disclaimer about seearch engine

- ui/apps/ui/src/app/components/search-bar/search-bar.component.ts
- ui/apps/ui/src/scss/landing.scss
- ui/apps/ui/src/styles.scss
> search box and user announcement aligment plus rwd

- transform/schemas/mappings.py
> fix: access type mapping

- backend/Pipfile
- backend/Pipfile.lock
- backend/app/middlewares.py
- backend/app/routes/web/auth.py
- backend/app/routes/web/user_actions.py
- backend/tests/app/routes/test_user_actions.py
- backend/tests/conftest.py
- backend/tests/utils.py
* Add tests for navigate endpoint
* Fix error log for anonymous session in user /me endpoint
> fix: user actions for signed-in user

- backend/app/config.py
- backend/app/routes/web/recommendation.py
- ui/apps/ui/src/app/components/recommendations/recommendations.service.ts
- ui/apps/ui/src/app/components/recommendations/recommendations.types.ts
> fix: recommender system

- backend/app/routes/web/recommendation.py
- ui/apps/ui/src/app/app.module.ts
- fix the `google analytics id` error while building the app
- replace `aai_id` with `aai_uid` name
- replace `other` with `other_research_product`
> fix: update recommendations fields

- ui/apps/ui/project.json
- ui/apps/ui/src/index.html
- ui/apps/ui/src/styles.scss
- ui/package-lock.json
- ui/package.json
* Move scripts from head to body
> feat: improve loading time

- transform/transformations/common.py
- transform/transformers/data_source.py
- transform/transformers/dataset.py
- transform/transformers/other_rp.py
- transform/transformers/publication.py
- transform/transformers/service.py
- transform/transformers/software.py
- transform/transformers/training.py
closes #437 
Remove commas from OAG and trainings authors
> feat: remove commas from authors

- transform/schemas/mappings.py
> feat: handle new trainings

- backend/app/routes/recommend.py
- backend/app/routes/search.py
- backend/app/routes/web/recommendation.py
- backend/app/routes/web/search.py
- backend/app/solr/operations.py
- backend/tests/app/routes/test_search.py
- transform/Pipfile
- transform/Pipfile.lock
- ui/apps/ui/src/app/collections/data/config.ts
- ui/apps/ui/src/app/collections/filters-serializers/utils.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/components/results-with-pagination/pagination.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/pagination.repository.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/app/components/search-bar/search-bar.component.ts
- ui/apps/ui/src/app/components/search-input/query.sanitizer.ts
- ui/apps/ui/src/app/components/search-input/search-input.component.ts
- ui/apps/ui/src/app/layouts/utils.ts
- ui/apps/ui/src/app/pages/acceptable-use-policy/acceptable-use-policy.component.html
- ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.component.html
- ui/apps/ui/src/app/pages/search-page/search-page.component.ts
- ui/apps/ui/src/index.html
- ui/apps/ui/src/styles.scss
- ui/package-lock.json
- search improvement
- tested on http://149.156.182.2:8983/solr and with NON facade recommender.
-goal: set KeywordTokenizer and add simple algo for KeywordTokenizer with ~2 maximum if more than 3 words with words size greater than 5. otherwise no fuzzy. case for ~1 also to be crafted. Important with KeywordTokenizer would be to add mm at 70-80%.
> feat: search improvements for #404 and #397 and #319

- ui/apps/ui/src/app/components/back-to-search-bar/back-to-search-bar.component.spec.ts
- ui/apps/ui/src/app/components/back-to-search-bar/back-to-search-bar.component.ts
- ui/apps/ui/src/app/components/back-to-search-bar/back-to-search-bar.module.ts
- ui/apps/ui/src/app/components/main-header/main-header.component.ts
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html
- ui/apps/ui/src/app/pages/trainings-page/trainings-page.module.ts
- ui/apps/ui/src/index.html
* Add go back to search header to trainings
* Link commons styles
> feat: [#2884-MP] Header Update

- backend/app/routes/web/recommendation.py
closes #462 
Expected behavior: 
- recommendations for services are NOT random in all catalogs & services collection,
- recommendations for data sources are STILL random.
> fix: [#462] recommendations for services

- README.md
- backend/app/config.py
- backend/app/routes/web/__init__.py
- backend/app/routes/web/configuration.py
- backend/app/schemas/configuration_response.py
- backend/tests/app/routes/test_configuration.py
- ui/apps/ui/src/app/app.module.ts
- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
- ui/apps/ui/src/app/collections/data/services/adapter.data.ts
- ui/apps/ui/src/app/pages/landing-page/landing-page.component.html
- ui/apps/ui/src/app/pages/landing-page/landing-page.component.ts
- ui/apps/ui/src/app/services/config-bootstrap.service.spec.ts
- ui/apps/ui/src/app/services/config.service.ts
To test custom redirections env variable `MARKETPLACE_BASE_URL` must be set (default is `https://marketplace.eosc-portal.eu`).
Closes #448
> feat: [#448] redirects to custom marketplace url

- ui/apps/ui/src/styles.scss
fix for topbar:
1. UHD fix
2. Black bottom border fix
> background fix for uhd

- ui/apps/ui/src/app/collections/services/custom-route.service.ts
- ui/apps/ui/src/app/collections/services/custom-route.type.ts
- ui/apps/ui/src/app/components/page-header/page-header.component.ts
- ui/apps/ui/src/app/components/page-header/page-header.module.ts
- ui/apps/ui/src/app/components/search-input/search-input.component.ts
- ui/apps/ui/src/app/components/sort-by-functionality/sort-by-functionality.component.ts
- ui/apps/ui/src/app/components/sort-by-functionality/sort-value.type.ts
- ui/apps/ui/src/app/pages/landing-page/landing-page.component.ts
> 461 add sort by functionality in the search service

- ui/apps/ui/src/app/pages/acceptable-use-policy/acceptable-use-policy.component.html
- ui/apps/ui/src/app/pages/acceptable-use-policy/acceptable-use-policy.module.ts
- ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.component.html
- ui/apps/ui/src/app/pages/privacy-policy/privacy-policy.module.ts
for the preview
https://github.com/cyfronet-fid/eosc-search-service/issues/483
> feat: #483 add new header with go to search service action

- ui/apps/ui/src/index.html
ENV variable should be set:
```
EOSC_COMMONS_URL=https://s3.cloud.cyfronet.pl/eosc-portal-common/pr-229-add-possibility-to-customize-privacy-policy-and-term-of-use-in-the-footer-per-service/
```
> feat: customized commons privacy policy and tos

- backend/app/recommender/router_utils/common.py
- backend/app/recommender/router_utils/recommendations.py
- backend/app/recommender/router_utils/sort_by_relevance.py
> feat: sort by relevance after facade adjustments

- ui/apps/ui/src/app/collections/filters-serializers/date.deserializer.ts
Fix is almost identical to #528.
Closes #278
> fix: [#278] Date does not disappear with other filters

- ui/apps/ui/src/app/collections/data/guidelines/filters.data.ts
- ui/apps/ui/src/app/components/active-filters/active-filters.component.ts
- ui/apps/ui/src/app/components/active-filters/active-filters.module.ts
- ui/apps/ui/src/app/components/active-filters/utils.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/checkboxes-tree.component.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/filter-multiselect.module.ts
- ui/apps/ui/src/app/components/filters/filters-layouts/filter-label.module.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/app/dictionary/IIGDictionary.interface.ts
- ui/apps/ui/src/app/dictionary/interoperabilityGuidelinesStatusDictionary.ts
- ui/apps/ui/src/app/dictionary/interoperabilityGuidelinesTypeDictionary.ts
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.html
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.ts
- ui/apps/ui/src/app/pages/guidelines-page/guidelines-page.module.ts
- ui/apps/ui/src/app/pages/search-page/search-page.component.ts
- ui/apps/ui/src/app/pipe/interoperability-guidelines-filter.pipe.ts
- ui/apps/ui/src/app/pipe/interoperability-guidelines.pipe.module.ts
https://github.com/cyfronet-fid/eosc-search-service/issues/544
> 544 filters for guidliness

- ui/apps/ui/src/app/components/recommendations/recommendations.component.html
- ui/apps/ui/src/app/components/recommendations/recommendations.component.scss
- ui/apps/ui/src/app/components/recommendations/recommendations.component.ts
- ui/apps/ui/src/app/components/recommendations/recommendations.module.ts
- ui/apps/ui/src/app/layouts/colored-tags/colored-tags.component.ts
- ui/apps/ui/src/app/layouts/description/description.component.ts
- ui/apps/ui/src/app/layouts/tags/tags.component.ts
- ui/apps/ui/src/app/pages/search-page/search-page.component.ts
https://github.com/cyfronet-fid/eosc-search-service/issues/557
> feat: #557 suggested move on the bottom

- ui/apps/ui/src/app/dictionary/translateDictionaryValue.ts
done, lowercase removed from origin value
> feat: #588 filter lowercase bug fixed

- transform/conf/spark.py
- transform/process.py
- transform/tests/utils/test_utils.py
- transform/transformations/common.py
- transform/transformers/__init__.py
- transform/transformers/base/base.py
- transform/transformers/base/marketplace.py
- transform/transformers/base/oag.py
- transform/transformers/bundle.py
- transform/transformers/data_source.py
- transform/transformers/dataset.py
- transform/transformers/guideline.py
- transform/transformers/offer.py
- transform/transformers/other_rp.py
- transform/transformers/provider.py
- transform/transformers/publication.py
- transform/transformers/service.py
- transform/transformers/software.py
- transform/transformers/training.py
- transform/utils/loader.py
- transform/utils/save.py
- transform/utils/send.py
- transform/utils/utils.py
> chore: [#591] simplify transform paths

- ui/apps/ui/src/app/app.routing.module.ts
- ui/apps/ui/src/app/collections/data/guidelines/filters.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/guideline.model.ts
- ui/apps/ui/src/app/collections/data/index.ts
- ui/apps/ui/src/app/components/recommendations/recommendations.component.ts
- ui/apps/ui/src/app/dictionary/dictionaryType.ts
- ui/apps/ui/src/app/dictionary/interoperabilityGuidelinesAuthorTypeDictionary.ts
- ui/apps/ui/src/app/dictionary/interoperabilityGuidelinesIdentifierTypeDictionary.ts
- ui/apps/ui/src/app/dictionary/interoperabilityGuidelinesResourceTypeGeneralDictionary.ts
- ui/apps/ui/src/app/dictionary/runDictionaryForInteroperabilityGuidelines.ts
- ui/apps/ui/src/app/dictionary/translateDictionaryValue.ts
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.html
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.scss
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.ts
- ui/apps/ui/src/app/pipe/interoperability-guidelines-filter.pipe.ts
- ui/apps/ui/src/styles.scss
https://github.com/cyfronet-fid/eosc-search-service/issues/571
> feat: #571 guidelines improvement

- README.md
- backend/app/config.py
- backend/app/dependencies/related_services.py
- backend/app/routes/web/__init__.py
- backend/app/routes/web/related_services.py
- backend/app/solr/operations.py
> feat: [#596] get related services for guidelines

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/all/filters.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/adapter.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/filters.data.ts
- ui/apps/ui/src/app/collections/data/shared-tags.ts
- ui/apps/ui/src/app/layouts/colored-tags/colored-tags.component.ts
colored (pink) tags beta in interoperability guidelines results added
> feat: #594 pink beta on guidelines

- ui/apps/ui/src/app/collections/data/all/excluded.data.ts
- ui/apps/ui/src/app/collections/data/all/filters.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/excluded.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/filters.data.ts
- ui/apps/ui/src/app/collections/data/datasets/excluded.data.ts
- ui/apps/ui/src/app/collections/data/datasets/filters.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/excluded.data.ts
- ui/apps/ui/src/app/collections/data/index.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/excluded.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/filters.data.ts
- ui/apps/ui/src/app/collections/data/publications/excluded.data.ts
- ui/apps/ui/src/app/collections/data/publications/filters.data.ts
- ui/apps/ui/src/app/collections/data/services/excluded.data.ts
- ui/apps/ui/src/app/collections/data/services/filters.data.ts
- ui/apps/ui/src/app/collections/data/software/excluded.data.ts
- ui/apps/ui/src/app/collections/data/software/filters.data.ts
- ui/apps/ui/src/app/collections/data/trainings/excluded.data.ts
- ui/apps/ui/src/app/collections/data/trainings/filters.data.ts
- ui/apps/ui/src/app/collections/data/validators.ts
- ui/apps/ui/src/app/collections/repositories/filters-configs.repository.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
> fix: [#597] Adjust ordering and naming of filters

- package-lock.json
- ui/apps/ui/proxy.external.conf.json
- ui/apps/ui/src/app/components/collections-navigation/collections-navigation.component.ts
- ui/apps/ui/src/app/components/recommendations/recommendations.component.html
- ui/apps/ui/src/app/components/recommendations/recommendations.component.scss
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.html
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.scss
- ui/apps/ui/src/app/pages/search-page/search-page.component.ts
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.scss
- ui/apps/ui/src/styles.scss
Added mods for mobile version of search results
#622
> Mobile view fix

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
> fix: #641 autocomplete urls broken

- ui/apps/ui/src/app/collections/data/all/filters.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/filters.data.ts
- ui/apps/ui/src/app/collections/data/datasets/filters.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/filters.data.ts
- ui/apps/ui/src/app/collections/data/publications/filters.data.ts
- ui/apps/ui/src/app/collections/data/services/filters.data.ts
- ui/apps/ui/src/app/collections/data/software/filters.data.ts
- ui/apps/ui/src/app/collections/data/trainings/filters.data.ts
- ui/apps/ui/src/app/collections/data/utils.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/filter-multiselect.component.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/first-n-values.component.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/show-all.component.ts
- ui/apps/ui/src/app/components/filters/filters.component.ts
- ui/apps/ui/src/app/components/filters/utils.ts
> feat: [#603] Make filters custom-sortable

- README.md
- backend/app/config.py
- backend/app/recommender/router_utils/common.py
- backend/app/recommender/router_utils/sort_by_relevance.py
- backend/app/routes/web/recommendation.py
- backend/app/routes/web/search.py
- backend/app/routes/web/user_actions.py
- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
- ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/adapter.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/adapter.data.ts
- ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
- ui/apps/ui/src/app/collections/data/services/adapter.data.ts
- ui/apps/ui/src/app/collections/data/software/adapter.data.ts
- ui/apps/ui/src/app/collections/data/trainings/adapter.data.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/collections/services/custom-route.service.ts
- ui/apps/ui/src/app/collections/services/custom-route.type.ts
- ui/apps/ui/src/app/components/page-header/page-header.component.ts
- ui/apps/ui/src/app/components/search-input/search-input.component.ts
- ui/apps/ui/src/app/components/sort-by-functionality/sort-by-functionality.component.ts
- ui/apps/ui/src/app/components/sort-by-functionality/sort-value.type.ts
- ui/apps/ui/src/app/pages/landing-page/landing-page.component.ts
- ui/apps/ui/src/app/pages/search-page/search-page.component.ts
> feat: [#636] Enable sort by date/popularity/relevance

- ui/apps/ui/src/app/components/active-filters/active-filters.component.ts
- ui/apps/ui/src/app/components/back-to-search-bar/back-to-search-bar.component.ts
- ui/apps/ui/src/app/components/collections-navigation/collections-navigation.component.ts
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.ts
* Fix back to search in trainings (for multiple keywords)
* Fix selecting keyword from trainings
Closes #638, #626
> fix: [#638, #626] Fix back to search in trainings

- backend/app/routes/web/recommendation.py
- backend/app/routes/web/search.py
- ui/apps/ui/src/app/components/sort-by-functionality/sort-by-functionality.component.ts
- ui/apps/ui/src/app/components/sort-by-functionality/sort-value.type.ts
> fix: [#656] sort by relevance

- backend/Pipfile.lock
- backend/app/dependencies/user_actions.py
- backend/app/routes/web/user_actions.py
- backend/tests/app/routes/test_user_actions.py
> feat: [#542] Forward user action details to other services

- ui/apps/ui/src/app/components/sort-by-functionality/sort-by-functionality.component.ts
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.html
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.scss
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.ts
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=60-2227&mode=design&t=V43vZlbG9qAFpD1v-0
> feat: #693 html structure changed

- backend/app/dependencies/user_actions.py
> fix: [#687] Make source_id different from unique_id

- ui/apps/ui/src/app/collections/data/datasets/filters.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/filters.data.ts
- ui/apps/ui/src/app/collections/data/publications/filters.data.ts
- ui/apps/ui/src/app/collections/data/software/filters.data.ts
- ui/apps/ui/src/app/collections/data/trainings/filters.data.ts
- ui/apps/ui/src/app/collections/filters-serializers/filters-serializers.utils.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/components/filters/filter-date/date-utils.ts
- ui/apps/ui/src/app/components/filters/filter-date/filter-date-calendar.component.ts
- ui/apps/ui/src/app/components/filters/filter-date/filter-date-calendar.module.ts
- ui/apps/ui/src/app/components/filters/filter-date/filter-date-year.component.ts
- ui/apps/ui/src/app/components/filters/filter-date/filter-date-year.module.ts
- ui/apps/ui/src/app/components/filters/filters.component.ts
- ui/apps/ui/src/app/components/filters/filters.module.ts
> feat: [#599] Change the date range filter to use year only

- backend/app/routes/web/search.py
- backend/app/schemas/search_request.py
- backend/app/schemas/web.py
- backend/app/solr/operations.py
- backend/tests/app/routes/test_search.py
- ui/apps/ui/src/app/collections/data/config.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/collections/services/fetch-data.service.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/filter-multiselect.service.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/utils.ts
- ui/apps/ui/src/app/components/filters/filter-range/filter-range.component.ts
- ui/apps/ui/src/app/components/filters/filter-range/filter-range.service.ts
- ui/apps/ui/src/app/components/filters/filter-range/utils.ts
- ui/apps/ui/src/app/components/filters/utils.ts
Closes #532.
Separated into 2 commits: backend and UI for ease of review. I can squash the commits later if needed.
----
@Marcelinna check the "trainings" tab in the "duration" filter for QA
> feat: [#532] Add dynamic fetching of max range

- solr/config/configsets/all_collection_13-07-2023/solrconfig.xml
> fix: [#730] solr schema 13.07

- solr/config/configsets/all_collection_25-07-2023/managed-schema
- transform/app/transform/transformers/guideline.py
closes #760 
@Anok666 please check if you have everything you need. And if the form of data is okay for you.
> feat: [#760] serialize creators for ig

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/adapter.data.ts
- ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
- ui/apps/ui/src/app/collections/data/software/adapter.data.ts
- ui/apps/ui/src/app/collections/data/utils.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/layouts/tags/tags.component.ts
Partially addresses #765 
@agpul I added only DOI for now. 
I cannot find other identifiers (HANDLE, PMID, PMD) in the data (perhaps @Michal-Kolomanski can help?)
NOTE: Styling will be addressed in other PR along with #785
> feat: [#765] Add link and subtitle to DOI

- backend/app/routes/web/search.py
Closes #754.
This is a workaround. Fix once bundles are presentable again.
How to test:
1. Go to /search/all
2. Bundles should be at the very bottom of the list (this will be impossible to check manually, unless you go through X amount of pages)
3. Bundles should still be present when you search for them.
> feat: [#754] Remove bundles from top of search

- ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
- ui/apps/ui/src/app/collections/data/software/adapter.data.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.html
- ui/apps/ui/src/app/layouts/tags/tags.component.ts
- ui/apps/ui/src/styles.scss
> feat: [#785] Expand results metadata

- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
Hot fix for the provider label in the result index view. Closes #843.
> fix: [#843] Add provider type result label

- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
Closes #266.
There was a typo when checking for duplicates in tags.
> fix: [#266] Fix duplicated filters

- ui/apps/ui/src/app/collections/data/data-sources/filters.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/filters.data.ts
- ui/apps/ui/src/app/collections/data/services/filters.data.ts
- ui/apps/ui/src/app/collections/data/trainings/filters.data.ts
> feat: [#819] Add language and license filters to services/igs

- backend/app/recommender/router_utils/recommendations.py
> fix: rs alias problem

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
- ui/apps/ui/src/app/collections/data/openair.model.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/adapter.data.ts
- ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
- ui/apps/ui/src/app/collections/data/software/adapter.data.ts
- ui/apps/ui/src/app/collections/data/trainings/adapter.data.ts
- ui/apps/ui/src/app/collections/data/utils.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.html
- ui/apps/ui/src/app/layouts/tags/tags.component.ts
Closes #765.
Also added a hotfix for doctype being visible again in publications.
> feat: [#765] Add pid handling for: HANDLE, PMID and PMC

- ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin-static.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin.component.scss
- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.html
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.module.ts
* Add pin to... to services, data-sources and bundles
> fix: revert bundle url

- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin-static.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin.component.ts
> feat: [#911] click pin to mp opens in new tab

- ui/apps/ui/src/app/components/feedback-panel/feedback-panel.component.html
- ui/apps/ui/src/app/components/feedback-panel/feedback-panel.component.scss
> feat: [#942] help button mods

- transform/app/api/routes/transform/full.py
- transform/app/main.py
- transform/app/services/mp_pc/data.py
- transform/app/services/solr/delete.py
- transform/app/services/solr/refresh.py
- transform/app/transform/mappings/scientific_doamin.py
- transform/app/transform/schemas/output/bundle.py
- transform/app/transform/schemas/output/data_source.py
- transform/app/transform/schemas/output/dataset.py
- transform/app/transform/schemas/output/guideline.py
- transform/app/transform/schemas/output/offer.py
- transform/app/transform/schemas/output/other_rp.py
- transform/app/transform/schemas/output/provider.py
- transform/app/transform/schemas/output/publication.py
- transform/app/transform/schemas/output/service.py
- transform/app/transform/schemas/output/software.py
- transform/app/transform/schemas/output/training.py
- transform/app/transform/transformers/bundle.py
- transform/app/transform/transformers/data_source.py
- transform/app/transform/transformers/dataset.py
- transform/app/transform/transformers/guideline.py
- transform/app/transform/transformers/offer.py
- transform/app/transform/transformers/other_rp.py
- transform/app/transform/transformers/provider.py
- transform/app/transform/transformers/publication.py
- transform/app/transform/transformers/service.py
- transform/app/transform/transformers/software.py
- transform/app/transform/transformers/training.py
- transform/app/worker.py
> feat: [#961] improve delete and get mechanisms during a transformer update

- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin.component.scss
- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/sources.component.html
- ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/sources.component.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.html
- ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.module.ts
- ui/apps/ui/src/styles.scss
> feat: Add Sources dropdown

- transform/app/worker.py
- transform/docker-compose.yml
> fix: [#963] dont close spark after update, reduce celery concurrency

- ui/apps/ui/src/app/components/bibliography/bibliography.component.html
- ui/apps/ui/src/app/components/feedback-panel/feedback-panel.component.html
- ui/apps/ui/src/app/pages/landing-page/landing-page.component.html
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.scss
- ui/apps/ui/src/assets/about.svg
- ui/apps/ui/src/index.html
- ui/apps/ui/src/styles.scss
- ui/package-lock.json
closes #912 
New look of training page:
> feat: [#912] new look of training page

- transform/Dockerfile
- transform/app/transform/schemas/properties/data.py
- transform/app/transform/transformers/guideline.py
- transform/app/transform/transformers/training.py
> fix: [#1001] handle alternative pids

- ui/apps/ui/src/styles.scss
Look of main menu tab in active state:
> fix: main menu hover state look

- docker-compose.yml
- ui/apps/ui/src/app/collections/filters-serializers/filters-serializers.utils.ts
- ui/apps/ui/src/app/components/filters/filter-multiselect/filter-multiselect.component.ts
- ui/apps/ui/src/app/components/filters/filters.service.ts
- ui/apps/ui/src/styles.scss
> fix: test PR

- ui/apps/ui/src/app/dictionary/dictionaryType.ts
- ui/apps/ui/src/app/dictionary/translateDictionaryValue.ts
> fix: change value displayed for year range filter

- ui/apps/ui/src/app/dictionary/dictionaryType.ts
- ui/apps/ui/src/app/dictionary/translateDictionaryValue.ts
> Type filter casing

- transform/app/api/routes/__init__.py
- transform/app/api/routes/solr/__init__.py
- transform/app/api/routes/solr/create_collections.py
- transform/app/api/routes/transform/batch.py
- transform/app/api/routes/transform/full.py
- transform/app/server.py
- transform/app/services/solr/collections.py
- transform/app/services/solr/configsets.py
- transform/app/tasks/batch.py
- transform/app/tasks/create_collections.py
- transform/app/transform/schemas/properties/env.py
- transform/app/validations/other.py
- transform/app/validations/solr.py
- transform/app/worker.py
Pull request created as a response to ticket #771.
Closes #771
> feat: [#771] add transformer endpoint for creating collections

- ui/apps/ui/src/app/collections/data/all/filters.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/filters.data.ts
- ui/apps/ui/src/app/collections/data/datasets/filters.data.ts
- ui/apps/ui/src/app/collections/data/other-resources-products/filters.data.ts
- ui/apps/ui/src/app/collections/data/publications/filters.data.ts
- ui/apps/ui/src/app/collections/data/services/filters.data.ts
- ui/apps/ui/src/app/collections/data/software/filters.data.ts
- ui/apps/ui/src/app/collections/data/utils.ts
- ui/apps/ui/src/app/collections/repositories/types.ts
Removed "geographical_availabilities" mapping because it seems like we no longer return "World" value.
> feat: [AdHoc] Fix missing onFetchNodes mappings

- transform/app/transform/transformers/base/oag.py
- transform/app/transform/utils/common.py
> feat: [#1084] remove prefix eosc_if from oag data

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
- ui/apps/ui/src/app/collections/data/services/adapter.data.ts
> fix: fix type of data source record in services tab

- ui/apps/ui/src/app/collections/data/services/nav-config.data.ts
- ui/apps/ui/src/app/components/sort-by-functionality/sort-by-functionality.component.ts
> feat: [#1103] turn off sort by rel - services, change its name

- backend/app/routes/web/search_results.py
- backend/app/utils/ig_related_services.py
- ui/apps/ui/src/app/components/results-with-pagination/result.component.html
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- pritns changed to logs
- logo support added
> fix: prints removed and logo added

- ui/apps/ui/src/app/collections/data/config.ts
> fix: [#1129] manual data source pids mapping

- transform/app/transform/mappings/datasources_pids.py
- transform/app/transform/utils/common.py
> feat: [#1127] map oag data sources pids - development

- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html
> fix: display dash if no data in training

- ui/apps/ui/src/app/components/sort-by-functionality/sort-by-functionality.component.ts
> fix: sorting names

- transform/app/api/routes/solr/create_collections.py
- transform/app/services/mp_pc/data.py
- transform/app/services/solr/refresh.py
- transform/app/settings.py
- transform/app/tasks/batch.py
- transform/app/tasks/create_collections.py
Pull request created as a response to a ticket #1191
Closes #1191
> feat: [#1191] Add project and organisation to the solr endpoints

- ui/apps/ui/src/app/collections/services/custom-route.utils.ts
- ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
- ui/apps/ui/src/app/components/search-input/search-input.component.html
- ui/apps/ui/src/app/components/search-input/search-input.component.scss
- ui/apps/ui/src/app/components/search-input/search-input.component.ts
- ui/apps/ui/src/app/components/search-input/search-input.service.ts
- ui/apps/ui/src/app/pages/adv-search-guide/adv-search-guide.component.html
- ui/apps/ui/src/app/pages/search-page/utils.ts
closes #1179 
README
- See which PIDs are used: https://docs.google.com/spreadsheets/d/14HXqPcuj6R-Di1WPRkGONFAAgC4K19R_iRLWMym4auY/edit#gid=0
Scope:
- This is a PoC version of the ticket's scope - search only by DOI
- Screenshots in the advance search guide are not updated - there are some screenshots that show a tooltip where DOI or PID value should be visible. I will update them at the end
- I am still working on searching by all available PIDs. Maybe I will find a solution
List of DOIs to work with (one "doi" - one record):
```
{
"doi":["10.1002/zaac.19221220116"]},
{
"doi":["10.5281/zenodo.1131261",
"10.5281/zenodo.1131260"]},
{
"doi":["10.2113/gsecongeo.6.1.13"]},
{
"doi":["10.3897/biss.7.110103"]},
{
"doi":["10.1097/00000441-191112000-00039"]},
{
"doi":["10.5281/zenodo.6037575", …
```
> feat: [#1179] search by doi

- transform/app/transform/transformers/training.py
Closes #1213 
I have arranged the mapping alphabetically and added a new one.
> fix: [#1213] add resource type mapping

- transform/app/api/routes/solr/__init__.py
- transform/app/api/routes/solr/create_aliases.py
- transform/app/api/routes/solr/create_collections.py
- transform/app/api/routes/solr/delete_collections.py
- transform/app/api/routes/transform/__init__.py
- transform/app/api/routes/transform/batch.py
- transform/app/api/routes/transform/full.py
- transform/app/main.py
- transform/app/services/s3/connect.py
- transform/app/services/spark/config.py
- transform/app/settings.py
- transform/app/transform/mappings/scientific_doamin.py
- transform/app/transform/schemas/input/__init__.py
- transform/app/transform/schemas/output/__init__.py
- transform/app/transform/transformers/bundle.py
- transform/app/transform/transformers/catalogue.py
- transform/app/transform/transformers/guideline.py
- transform/app/transform/transformers/offer.py
- transform/app/transform/transformers/project.py
- transform/app/transform/transformers/training.py
Closes #1212 
In addition to adding mapping for scientific domains, `black .` was used to format other files.
> fix: [#1212] training scientific domain

- ui/apps/ui/src/app/components/results-with-pagination/result.component.html
> fix: change icon to catalogue logo

- transform/app/services/jms/connector.py
- transform/app/services/solr/validate.py
- transform/app/transform/live_update/training_ig.py
> feat: [#1275] enhance live update

- transform/app/services/solr/validate.py
> debug: debug solr url

- transform/Pipfile
- transform/Pipfile.lock
- transform/app/logger.py
- transform/app/server.py
- transform/app/services/jms/connector.py
- transform/app/services/solr/validate.py
- transform/app/transform/live_update/training_ig.py
- transform/app/transform/transformers/base/marketplace.py
- transform/app/worker.py
- transform/docker-compose.yml
closes #1297 
Scope:
- terminal logging: 
- INFO: simple logging
- WARNING...: detailed logging
- file logging: detailed logging
```
"class": "logging.handlers.RotatingFileHandler",
"maxBytes": 1024 * 1024 * 50,  # 50 MB
"backupCount": 5,  # keep at most 5 log files 
```
- nice formatting 
- colored logs
> feat: [#1297] configure logger

- transform/app/services/jms/connector.py
- transform/app/transform/schemas/input/training.py
> feat: [#1295] fix subscription issue

- ui/apps/ui/src/app/pages/search-page/search-page.component.html
- ui/apps/ui/src/styles.scss
Suspension information
Closes: #1302
> add top info banner

- ui/apps/ui/src/app/pages/search-page/search-page.component.html
- ui/apps/ui/src/styles.scss
Added new text due to Figma: https://www.figma.com/file/FtUWM7XIQklFKAoabpt4ta/Baner-EOSC?node-id=9124%3A100&mode=dev
> top banner text mods

- transform/Pipfile
- transform/Pipfile.lock
- transform/app/api/routes/transform/batch.py
- transform/app/services/jms/connector.py
- transform/app/settings.py
- transform/app/tasks/delete_data_by_id.py
- transform/app/transform/live_update/data_type_handlers.py
- transform/pytest.ini
- transform/tests/services/jms/conftest.py
- transform/tests/services/jms/test_async_behavior.py
- transform/tests/services/jms/test_configuration_handling.py
- transform/tests/services/jms/test_connection_management.py
- transform/tests/services/jms/test_message_handling.py
- transform/tests/services/jms/test_subscription_management.py
- transform/tests/transform/live_update/conftest.py
- transform/tests/transform/live_update/test_training_ig.py
Closes #1300 
Added complex tests for [app/services/jms/connector.py](https://raw.githubusercontent.com/cyfronet-fid/eosc-search-service/development/transform/app/services/jms/connector.py) and [app/transform/live_update/training_ig.py](https://raw.githubusercontent.com/cyfronet-fid/eosc-search-service/development/transform/app/transform/live_update/training_ig.py).
> feat: [#1300] tests for jms subscriber

- transform/app/services/mp_pc/data.py
> fix: [#1317] provider mapping

- ui/apps/ui/src/app/pages/search-page/search-page.component.html
- ui/apps/ui/src/styles.scss
> feat: [#1330] delete eosc message

- ui/apps/ui/src/app/collections/data/providers/filters.data.ts
> Change label for provider tags active filter

- README.md
- backend/Pipfile
- backend/Pipfile.lock
- backend/app/server.py
- backend/app/settings.py
> feat: add Sentry integration

- transform/schemas/db/dataset.py
- transform/schemas/db/other_rp.py
- transform/schemas/db/publication.py
- transform/schemas/db/software.py
> feat: [#1358] add db oag schemas

- .readthedocs.yaml
This PR is test for readthedocs configuration file
> feat: [#1360] readthedocs configuration

- .readthedocs.yaml
- transform/docs/requirements.txt
- transform/schemas/db/bundle.py
- transform/schemas/db/catalogue.py
- transform/schemas/db/data_source.py
- transform/schemas/db/dataset.py
- transform/schemas/db/guideline.py
- transform/schemas/db/offer.py
- transform/schemas/db/organisation.py
- transform/schemas/db/other_rp.py
- transform/schemas/db/project.py
- transform/schemas/db/provider.py
- transform/schemas/db/publication.py
- transform/schemas/db/service.py
- transform/schemas/db/software.py
- transform/schemas/db/training.py
- transform/schemas/se/bundle.py
- transform/schemas/se/catalogue.py
- transform/schemas/se/data_source.py
- transform/schemas/se/dataset.py
- transform/schemas/se/guideline.py
- transform/schemas/se/offer.py
- transform/schemas/se/organisation.py
- transform/schemas/se/other_rp.py
- transform/schemas/se/project.py
- transform/schemas/se/provider.py
- transform/schemas/se/publication.py
- transform/schemas/se/service.py
- transform/schemas/se/software.py
- transform/schemas/se/training.py
> fix: [#1360] fix readthedocs documentation

- README.md
- backend/app/recommender/router_utils/recommendations.py
- backend/app/routes/recommend.py
- backend/app/routes/search.py
- backend/app/routes/web/presentable.py
- backend/app/routes/web/recommendation.py
- backend/app/routes/web/research_product.py
- backend/app/routes/web/search_filters.py
- backend/app/routes/web/search_results.py
- backend/app/routes/web/search_suggestions.py
- backend/app/solr/operations.py
- backend/app/utils/ig_related_services.py
- backend/tests/app/data/test_search.post.response.json
- backend/tests/app/routes/test_search.py
- backend/tests/app/routes/test_search_filters.post.response.json
- backend/tests/app/routes/test_search_filters.py
- backend/tests/app/routes/test_suggestions.py
- ui/apps/ui/src/app/app.module.ts
- ui/apps/ui/src/app/collections/data/index.ts
- ui/apps/ui/src/app/collections/repositories/adapters.repository.ts
- ui/apps/ui/src/app/collections/repositories/filters-configs.repository.ts
- ui/apps/ui/src/app/collections/repositories/nav-configs.repository.ts
- ui/apps/ui/src/app/collections/repositories/search-metadata.repository.ts
- ui/apps/ui/src/app/collections/services/collections-prefix.interceptor.ts
- ui/apps/ui/src/app/components/top-menu/top-menu.component.html
- ui/apps/ui/src/app/components/top-menu/top-menu.component.scss
- ui/apps/ui/src/app/components/top-menu/top-menu.component.ts
- ui/apps/ui/src/app/services/initialize-collections-prefix.service.ts
Closes #1382 
@Michal-Kolomanski seems like the schemas are still mismatched (At least on the beta SOLR)
Publication and Services do not exist on the Beta SOLR
Expected schemas for filters for all 4 collections also do not work
> Add buttons for changing data scope context #1382

- transform/app/settings.py
> chore: pl eosc variables in settings

- backend/app/settings.py
- ui/apps/ui/src/app/collections/data/config.ts
- ui/apps/ui/src/app/components/top-menu/top-menu.component.ts
> 1389 infinite loading pl context

- ui/apps/ui/src/app/collections/data/config.ts
- ui/apps/ui/src/app/collections/data/index.ts
- ui/apps/ui/src/app/collections/repositories/search-metadata.repository.ts
- ui/apps/ui/src/app/components/top-menu/top-menu.component.ts
- ui/apps/ui/src/app/services/initialize-collections-prefix.service.ts
> feat: [#1417] add data sources in the PL context

- README.md
- backend/app/settings.py
- backend/tests/app/routes/test_configuration.py
> fix: [#1408] knowledge hub sandbox link

- transform/app/api/schemas/transform/dump.py
- transform/app/mappings/mappings.py
- transform/app/services/celery/task.py
- transform/app/services/celery/task_statuses.py
- transform/app/services/s3/connect.py
- transform/app/services/s3/get_s3_paths.py
- transform/app/services/s3/utils.py
- transform/app/services/s3/validate.py
- transform/app/settings.py
- transform/app/tasks/solr/create_aliases.py
- transform/app/tasks/solr/create_collections.py
- transform/app/tasks/solr/delete_collections.py
- transform/app/tasks/solr/delete_data_by_id.py
- transform/app/tasks/transform/dump/load.py
- transform/app/tasks/transform/dump/process.py
- transform/app/tasks/transform/dump/validate.py
- transform/app/tasks/utils/s3_paths.py
- transform/app/transform/transformers/training.py
- transform/app/transform/utils/common.py
- transform/app/worker.py
- transform/docker-compose.yml
- transform/docs/conf.py
> feat: [#1401] load data from cloud (s3)

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/index.ts
- ui/apps/ui/src/app/collections/pl-data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/pl-data/datasets/adapter.data.ts
> fix: [#1428] fix rodbuk redirections

- ui/apps/ui/src/app/components/top-menu/top-menu.component.ts
> 1440 fix reloading after clik on already chosen scope

- backend/app/settings.py
- backend/tests/app/routes/test_configuration.py
> feat: explore, mp default addresses

- transform/app/services/s3/get_s3_paths.py
- transform/app/services/s3/load.py
- transform/app/services/s3/utils.py
- transform/app/services/s3/validate.py
- transform/app/settings.py
- transform/app/tasks/solr/create_collections.py
- transform/app/tasks/transform/dump/load.py
- transform/app/tasks/transform/dump/process.py
- transform/app/tasks/transform/dump/transform.py
- transform/app/tasks/utils/s3_paths.py
- transform/app/transform/transformers/organisation.py
- transform/app/transform/transformers/project.py
Closes #1434 
There's an issue reading JSON files from S3. The current solution excludes problematic records.
Some problematic characters were observed in dataset/part-00000.json.
Fastest error recreation:
```
def connect_to_s3(access_key: str, secret_key: str, endpoint: str) -> boto3.client:
"""Connect to s3"""
session = boto3.session.Session()
s3_client = session.client(
service_name="s3",
aws_access_key_id=access_key,
aws_secret_access_key=secret_key,
endpoint_url=endpoint,
)
return s3_client 
s3_client = connect_to_s3(S3_ACCESS_KEY, S3_SECRET_KEY, str(S3_ENDPOINT))
key = 'test/dataset/part-00000.json'
s3_object = s3_client.get_object(Bucket=S3_BUCKET, Key=key)
s3_object_body = s3_object.get('Body')
content = s3_object_body.read()
content_str = content.decode('utf-8')
```
and …
> feat: [#1434] read and transform dump

- transform/.env.template
- transform/README.rst
- transform/app/api/endpoints/solr/create_aliases.py
- transform/app/api/endpoints/solr/create_collections.py
- transform/app/api/endpoints/solr/delete_collections.py
- transform/app/api/endpoints/transform/dump.py
- transform/app/api/schemas/transform/dump.py
- transform/app/services/mp_pc/data.py
- transform/app/services/s3/get_s3_paths.py
- transform/app/services/s3/send.py
- transform/app/services/s3/utils.py
- transform/app/services/solr/collections.py
- transform/app/services/solr/send.py
- transform/app/services/solr/utils.py
- transform/app/services/solr/validate/endpoints/validate.py
- transform/app/settings.py
- transform/app/tasks/solr/create_collections.py
- transform/app/tasks/transform/batch.py
- transform/app/tasks/transform/dump/process.py
- transform/app/tasks/transform/dump/transform.py
- transform/app/tasks/transform/dump/validate.py
- transform/app/tasks/utils/s3_paths.py
- transform/app/tasks/utils/save_error_log.py
- transform/app/tasks/utils/send.py
- transform/app/transform/transformers/project.py
- transform/app/transform/utils/common.py
- transform/app/transform/utils/send.py
- transform/app/transform/utils/utils.py
- transform/schemas/old/input/software.py
> feat: [#1435] send data

- backend/app/utils/ig_related_services.py
> fix: [#1479] ig detail page on services fail

- ui/apps/ui/proxy.external.conf.json
> fix: [#1495] backend address in proxy external

- backend/app/settings.py
> fix: [#1550] oidc_host default value

- ui/apps/ui/src/app/collections/data/all/adapter.data.ts
- ui/apps/ui/src/app/collections/data/all/filters.data.ts
- ui/apps/ui/src/app/collections/data/catalogues/adapter.data.ts
- ui/apps/ui/src/app/collections/data/catalogues/catalogue.model.ts
- ui/apps/ui/src/app/collections/data/catalogues/filters.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
- ui/apps/ui/src/app/collections/data/data-sources/data-source.model.ts
- ui/apps/ui/src/app/collections/data/data-sources/filters.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/adapter.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/filters.data.ts
- ui/apps/ui/src/app/collections/data/guidelines/guideline.model.ts
- ui/apps/ui/src/app/collections/data/providers/adapter.data.ts
- ui/apps/ui/src/app/collections/data/providers/filters.data.ts
- ui/apps/ui/src/app/collections/data/providers/provider.model.ts
- ui/apps/ui/src/app/collections/data/services/adapter.data.ts
- ui/apps/ui/src/app/collections/data/services/filters.data.ts
- ui/apps/ui/src/app/collections/data/services/service.model.ts
- ui/apps/ui/src/app/collections/data/trainings/adapter.data.ts
- ui/apps/ui/src/app/collections/data/trainings/filters.data.ts
- ui/apps/ui/src/app/collections/data/trainings/training.model.ts
- ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.html
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html
- ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.ts
> feat: [#1570] display node as multiselect filter, tag, in detail page 

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
So far only the documentation for the bronze badge, will add more later for silver and gold
> feat: [#1628] Add documentation needed for bronze SQA badge
