backend/app/routes/__init__.py
backend/app/routes/search.py
backend/app/schemas/recommend_request.py
backend/app/schemas/search_request.py
backend/app/solr/operations.py
backend/tests/test_apis.py

Switch to Solr's JSON Request API and use JSON Facet API
for the facets. In this way all parameters are passed to Solr
by JSON request body.
Closes: #25.

feat: expose facets in search endpoint

---

transform/all_collection/spark/process.py
transform/all_collection/spark/schemas/harvested_props_schemas.py
transform/all_collection/spark/schemas/input_col_name.py
transform/all_collection/spark/transformations/commons.py
transform/all_collection/spark/transformations/datasets_transform.py
transform/all_collection/spark/transformations/publications_transfrom.py
transform/all_collection/spark/transformations/services_transform.py
transform/all_collection/spark/transformations/software_transfrom.py
transform/all_collection/spark/transformations/trainings_transform.py
transform/all_collection/spark/utils/join_dfs.py

closes #225
Mapping as it was in the ticket (right side was mapped to the left side):
```
"Open access": "OPEN", "open_access", "fully_open_access", "open access", "free access", "free access "  - as you can see free access is twice (once with a space at the end) as always trainings data is flawed :)
"Restricted": "RESTRICTED"
"Ordered required": "order_required"
"Login required": "login required"
"Login required on EOSC Pillar, open access on the original resource page": "login required on EOSC Pillar, open access on the original resource page"
"Closed": "CLOSED"
"Embargo": "EMBARGO"
"Other": "other"
```

feat: mapping of access rights

---

ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
ui/apps/ui/src/app/collections/data/software/adapter.data.ts
ui/apps/ui/src/app/collections/data/trainings/adapter.data.ts

Issue: #220 
More details about implementation are covered in the issue comment:
https://github.com/cyfronet-fid/eosc-search-service/issues/220#issuecomment-1294795101
To filter resources containing certain fields in the catalog:
1. remove all filters
2. add `&fq=<field_name>:[* TO *]`
In our case:
- `publication_date`, `&fq=publication_date:[* TO *]`
Example: `https://eosc-search-service.grid.cyfronet.pl/search/training?q=*&fq=publication_date:[* TO *]`
- `fos`, `&fq=fos:[* TO *]`
Example: `https://eosc-search-service.grid.cyfronet.pl/search/publication?q=*&fq=fos:[* TO *]`
- `license`, `&fq=license:[* TO *]`
Example: `https://eosc-search-service.grid.cyfronet.pl/search/publication?q=*&fq=license:[* TO *]`
Filters updates in `All catalog` is affected by a missing feature to show …

fix: update tags fields

---

.env.template
README.md
ui/apps/ui/src/app/collections/data/all/search-metadata.data.ts
ui/apps/ui/src/app/collections/data/datasets/search-metadata.data.ts
ui/apps/ui/src/app/collections/data/publications/search-metadata.data.ts
ui/apps/ui/src/app/collections/data/services/search-metadata.data.ts
ui/apps/ui/src/app/collections/data/software/search-metadata.data.ts
ui/apps/ui/src/app/collections/data/trainings/search-metadata.data.ts
ui/apps/ui/src/environments/environment.common.ts

- add prefixes to collections, by default `NG_COLLECTIONS_PREFIX=''`
Building pipe updates for @wziajka 
Example: `NG_COLLECTIONS_PREFIX=prod_` for `production`
closes #307

chore: add configurable prefix to collections

---

ui/apps/ui/src/app/components/results-with-pagination/pagination.repository.ts
ui/apps/ui/src/app/components/results-with-pagination/pagination.service.ts
ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.ts

The issue was that the currentPage was not set after additional results were fetched (which happens on every 5th page, due to set constants).
Due to invalid page setting when fetching new results, this also caused the paginaton to be broken and in some cases one page would be overwritten and results were lost the user (!) - fixed that as well.
Closes #241

[#241] Fix pagination bug on every 5th page

---

ui/apps/ui/src/app/collections/filters-serializers/filters-serializers.utils.ts
ui/apps/ui/src/app/collections/filters-serializers/range.deserializer.ts

Deserialization assumed that the input will be of [number, number] type. This is not the case when the string was serialized to `00:00:00 TO HH:MM:SS` format. 
Changed the deserialization so that it can take the second format as well.
Closes #283

fix: [#283] Range does not disappear with other filters

---

ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.ts

User is now redirected to the top after chaging the page.
Closes #524

fix: [#524] User is redirected to the top of the page after pagination

---

ui/apps/ui/src/app/collections/services/redirect.service.ts
ui/apps/ui/src/app/components/recommendations/recommendations.component.html

The issue was that in the recommendation panel, there was no flag specifying that the user clicked the actual recommendation panel.
Closes #428

fix: [#428] Recommendation panel user action root content fixed

---

.github/workflows/backend-styles.yml
README.md
backend/app/config.py
backend/app/routes/web/configuration.py
backend/app/schemas/configuration_response.py
backend/tests/app/routes/test_configuration.py
ui/apps/ui/src/app/collections/data/all/adapter.data.ts
ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
ui/apps/ui/src/app/collections/data/other-resources-products/adapter.data.ts
ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
ui/apps/ui/src/app/collections/data/software/adapter.data.ts
ui/apps/ui/src/app/collections/services/redirect.service.ts
ui/apps/ui/src/app/services/config.service.ts

@wziajka should set `EOSC_EXPLORE_URL` env variable to explore beta: `https://beta.explore.eosc-portal.eu` (on the backend API container)
* Add configurable explore url 
* Url encode pv parameter

feat: Add configurable explore url

---

ui/apps/ui/src/app/components/filters/filter-multiselect/utils.ts

Closes #169 
Well, I'm not really sure what is meant by "improve" in the issue ticket, I noticed, however, that the results were sometimes really far away from the actual search query so I've raised the default threshold for the fuzzy search options - so now results should be much stricter in terms of search query (TLDR: less random results) 
More info: https://www.fusejs.io/api/options.html#threshold

fix: [#169] Tighten fuzzy search in filter search

---

ui/apps/ui/src/app/components/filters/filter-multiselect/show-all.component.ts

Closes #651 
The filter wouldn't show all values at once because they were dynamically fetched (from memory, not backend), but the scroll percentage was calculated using some hardcoded values and I guess something has changed during development.
Changed so now it is generic and works on all viewport sizes.

 fix: [#651] Multiselect 'show all' button doesn't show all data

---

README.md
backend/app/routes/web/configuration.py
backend/app/schemas/configuration_response.py
backend/app/settings.py
backend/tests/app/routes/test_configuration.py
ui/apps/ui/src/app/collections/data/providers/adapter.data.ts
ui/apps/ui/src/app/components/recommendations/recommendations.component.ts
ui/apps/ui/src/app/components/sort-by-functionality/sort-by-functionality.component.ts
ui/apps/ui/src/app/pages/search-page/search-page.component.ts
ui/apps/ui/src/app/services/config.service.ts
ui/apps/ui/src/environments/environment.common.ts
ui/apps/ui/src/environments/environment.prod.ts
ui/apps/ui/src/environments/environment.ts

closes #752
There is a new backend env variable called `IS_SORT_BY_RELEVANCE`. By default, it is set to `False` (now for testing purposes is set to True for @Marcelinna).
@wziajka please set (after merging this PR):
- on beta/PR instances: `IS_SORT_BY_RELEVANCE=True`
- on the production instance, no action is needed, but I suggest setting either way  `IS_SORT_BY_RELEVANCE=False` to be more transparent for future reference. 
@Marcelinna please test this PR.
- Currently, I set `IS_SORT_BY_RELEVANCE=True` (using default) - please look at the instance and confirm that sort by relevance is enabled in proper collections. Then ping me and leave a comment here.
- Secondly, I will set `IS_SORT_BY_RELEVANCE=False`. Once again then, I will ask you to check if sort by relevance is disabled in all …

fix: [#752] fix sort by rel beta

---

backend/app/recommender/router_utils/recommendations.py
backend/app/recommender/router_utils/sort_by_relevance.py
backend/app/routes/web/recommendation.py
backend/app/routes/web/search.py

closes #696 
The scope is to include the aai_uid of a user in sort by relevance requests. 
I tested that on the PR instance:
- sort by relevance request message from the databus:
```
{'context': {'aai_uid': 'd17380a3d98a019a44ffa6fe9be9f7237359a4300c076a1ee85ff78b5b6b9bc1@egi.eu',
...}
```
- standard recommendations request:
```
{'context': {'aai_uid': 'd17380a3d98a019a44ffa6fe9be9f7237359a4300c076a1ee85ff78b5b6b9bc1@egi.eu',
...}
```
- user_actions
```
("aai_uid": '
'"d17380a3d98a019a44ffa6fe9be9f7237359a4300c076a1ee85ff78b5b6b9bc1@egi.eu"}')
```
As you can see, everywhere aai_uid is the same. Furthermore, I asked @wziajka to confirm whether that aai_uid is my true aai_uid (in beta MP's DB) and it is proper aai_uid.

fix: [#696] aai_uid in sort by relevance

---

ui/apps/ui/src/styles.scss

Added fix for long result titles without any space in one line:
Closes: #888

fix for long names without space

---

ui/apps/ui/src/app/collections/filters-serializers/filters-serializers.utils.ts

Filters config sometimes is undefined when the user quickly changes collections (looks like 'trainings' tab is triggering the error)

bug: fix undefined filterConfig

---

backend/app/dependencies/user_actions.py
backend/app/recommender/router_utils/recommendations.py
backend/app/routes/web/recommendation.py
backend/app/routes/web/user_actions.py

Closes #928.
recommendation_visit_id is stored in Cookies for the user action request to retrieve it if it's root is in the recommendation panel

feat: [#928] Correlate visit_id from recommendations with user actions

---

ui/apps/ui/src/app/collections/data/guidelines/filters.data.ts
ui/apps/ui/src/app/collections/data/trainings/filters.data.ts
ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.html
ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html

closes #1009 
Scope:
1) html in guidelines and training descriptions should be handled. Guideline that has HTML [link](https://search-6.docker-fid.grid.cyf-kr.edu.pl/guidelines/eosc.85d3f1ab01e8fa7070a5a30f3b504644?return_path=search%2Fguideline&search_params=q%3D*%26standard%3Dtrue%26exact%3Dfalse%26radioValueAuthor%3DA%26radioValueExact%3DA%26radioValueTitle%3DA%26radioValueKeyword%3DA&source_id=68e03658-fa3d-466a-9a83-0e593333e2a6&client_uid=bc58a410-1763-4200-b01e-51e707281144)
2) the same good-looking description in guidelines as it is in trainings (About)
3) providers -> organizations data switch in trainings organizations filter 
4) rename domain -> scientific domains filter in guidelines
5) keywords in trainings detail page are shown when their len >  0. Training that has 0 …

feat: guidelines & trainings minor improvements

---

README.md
backend/app/routes/web/configuration.py
backend/app/routes/web/search_results.py
backend/app/schemas/configuration_response.py
backend/app/settings.py
backend/tests/app/routes/test_configuration.py
ui/apps/ui/src/app/pages/search-page/utils.ts

closes #1121 
- powrot do zaciagania 50 resourcow (5 pages) na raz,
- do sort by relevance nadal leci 250 resourcow - stworzylem zmienna srodowiskowa do latwej manipulacji tej liczby
Jak testowac?
- powinien sie zmniejszyc czas dociagania search-results - mozna to podejrzec w network. Porownujmy ten czas z beta.
- warto zwrocic uwage, ze czas dociagania filtrow sie nie zmniejszyl (request search-filters), wiec zdarza sie sytuacja w ktorej rezultaty sie juz dawno temu dociagnely, ale nadal strona czeka na filtry
- zauwazylem, ze pierwsze dociagniecie danych w danej zakladce jest zdecydowanie wolniejsze,
- najwolniejsze kolekcje to zdecydowanie all_collection, publication oraz dataset

feat: [#1121] speed up search

---

backend/app/consts.py
backend/app/routes/web/user_actions.py
backend/app/solr/operations.py
backend/tests/app/routes/test_suggestions.py
ui/apps/ui/src/app/collections/data/catalogues/adapter.data.ts
ui/apps/ui/src/app/collections/data/catalogues/catalogue.model.ts
ui/apps/ui/src/app/collections/data/catalogues/excluded.data.ts
ui/apps/ui/src/app/collections/data/catalogues/filters.data.ts
ui/apps/ui/src/app/collections/data/catalogues/nav-config.data.ts
ui/apps/ui/src/app/collections/data/catalogues/search-metadata.data.ts
ui/apps/ui/src/app/collections/data/config.ts
ui/apps/ui/src/app/collections/data/index.ts
ui/apps/ui/src/app/collections/data/organisations/nav-config.data.ts
ui/apps/ui/src/app/collections/repositories/types.ts
ui/apps/ui/src/app/components/recommendations/recommendations.component.ts
ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/show-related-resources.ts
ui/apps/ui/src/app/components/results-with-pagination/result.component.html
ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.html
ui/apps/ui/src/app/components/search-input/search-input.component.html
ui/apps/ui/src/app/components/search-input/search-input.component.ts
ui/apps/ui/src/app/components/sort-by-functionality/sort-by-functionality.component.ts
ui/apps/ui/src/app/components/top-menu/top-menu.component.html
ui/apps/ui/src/styles.scss

1. Catalogue collection is added as a tab in the top panel
2. redirection to all_catalogues with the chosen catalogue as a filter
3. redirection to mp for the detail view
4. search by abbreviation added also to provider, project and organisation collections

feat: add catalogues collection

---

backend/app/consts.py
backend/tests/app/routes/test_suggestions.py

closes #1200 
- auto-suggestion didn't work only in `all_collection` 
- that was the case because we were performing exactly the same search for each data type (collection) **including** new collection: `organisation` 
- we cannot perform a standard search (`title^100 author_names_tg^120 description^10 keywords_tg^10 tag_list_tg^10`) on an organisation collection that doesn't have those properties.
Scope:

fix: [#1200] auto suggestion

---

ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/show-related-resources.scss
ui/apps/ui/src/app/layouts/share/share.component.scss
ui/apps/ui/src/styles.scss

Fix for "Show resources" link in bottom line:

show resources link mod

---

ui/apps/ui/src/app/collections/data/all/adapter.data.ts
ui/apps/ui/src/app/collections/data/services/adapter.data.ts
ui/apps/ui/src/app/collections/data/services/service.model.ts
ui/apps/ui/src/app/pages/search-page/search-page.component.html

fix: [#1420] handle services without pid

---

backend/app/routes/web/configuration.py
backend/app/schemas/configuration_response.py
backend/app/settings.py
backend/tests/app/routes/test_configuration.py
ui/apps/ui/src/app/collections/data/all/adapter.data.ts
ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
ui/apps/ui/src/app/collections/data/catalogues/adapter.data.ts
ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
ui/apps/ui/src/app/collections/data/index.ts
ui/apps/ui/src/app/collections/data/providers/adapter.data.ts
ui/apps/ui/src/app/collections/data/services/adapter.data.ts
ui/apps/ui/src/app/collections/pl-data/all/adapter.data.ts
ui/apps/ui/src/app/collections/pl-data/data-sources/adapter.data.ts
ui/apps/ui/src/app/collections/pl-data/providers/adapter.data.ts
ui/apps/ui/src/app/collections/pl-data/services/adapter.data.ts
ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin.component.ts
ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.ts
ui/apps/ui/src/app/layouts/ig-services-card/ig-services-card.component.ts
ui/apps/ui/src/app/layouts/ig-services-card/ig-services-detail-card.component.ts
ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.ts
ui/apps/ui/src/app/pages/search-page/search-page.component.ts
ui/apps/ui/src/app/services/config.service.ts

feat: [#1438] mp redirects

---

ui/apps/ui/src/app/collections/data/all/adapter.data.ts
ui/apps/ui/src/app/collections/data/catalogues/adapter.data.ts
ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
ui/apps/ui/src/app/collections/data/providers/adapter.data.ts
ui/apps/ui/src/app/collections/data/services/adapter.data.ts
ui/apps/ui/src/app/collections/data/services/service.model.ts
ui/apps/ui/src/app/collections/data/url-builder-utils.ts

closes #1645
Resources onboarded directly in MP doesnt have a PID. We should use PID and fallback to Slug.
PID or Slug collection Scope:
Repo Scope:

Fix: [#1645] use pid or slug

---

solr/config/configsets/all_collection_v210/configoverlay.json
solr/config/configsets/all_collection_v210/managed-schema
ui/apps/ui/src/app/collections/data/adapters/adapter.data.ts
ui/apps/ui/src/app/collections/data/adapters/adapter.model.ts
ui/apps/ui/src/app/collections/data/adapters/filters.data.ts
ui/apps/ui/src/app/collections/repositories/types.ts
ui/apps/ui/src/app/components/repository/repository.component.ts
ui/apps/ui/src/app/components/results-with-pagination/result.component.html
ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.html
ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.module.ts
ui/apps/ui/src/app/pages/adapters-page/adapter-detail-page.component.html
ui/apps/ui/src/app/pages/adapters-page/adapter-detail-page.component.scss
ui/apps/ui/src/app/pages/adapters-page/adapter-detail-page.component.ts
ui/apps/ui/src/app/pages/adapters-page/adapters-page.module.ts
ui/apps/ui/src/app/pages/adapters-page/slice-release.pipe.ts

closes #1632
Improvements:
List View:
Detail View: 
Still missing:
- https://github.com/cyfronet-fid/eosc-search-service/issues/1653
- https://github.com/cyfronet-fid/eosc-search-service/issues/1652
Changes on transformer side
https://github.com/cyfronet-fid/transform-service/pull/71
Adapter's output from solr:
```
{
"catalogues":["eosc"],
"changelog":["https://platform.openai.com/"],
"description":["<p>Test adapter</p>"],
"documentation_url":["https://platform.openai.com/docs/guides/text?api-mode=responses"],
"id":"21.15126/CWTM65",
"keywords":["llm, chatgpt"],
"license":"adapter_license-apache2",
"logo":"https://i0.wp.com/www.getautismactive.com/wp-content/uploads/2021/01/Test-Logo-Circle-black-transparent.png?fit=1200%2C1200&ssl=1&w=640",
"node":"Sandbox", …
```

fix: [#1632] adapters enhancements
